### ISSUE TITLE
Fractional Vegetation Cover Formula

### ISSUE THREAD

**Issue by jeafreezy** [pylandtemp/pylandtemp#2]
Hi @dimejimudele ,I must commend the great effort and man-hour you have put into this script. It's such an awesome one and it's really helpful.

However, while going through the script, I got confused at the function for calculating the LSE from FVC, there, I found out that the formula you used for the FVC==> (NDVI-NDVImin)/(NDVImax-NDVImin)**2 looks different from the formula I have seen in various researches==> (NDVI-NDVIs)/(NDVIs-NDVIv) where NDVIs is the NDVI of bare soil and NDVI v is the NDVI of vegetation. I went ahead to look up the research paper you attached in the function docstrings too, but I did not find the formula you used there. 
I'm not saying the formula is wrong, maybe it's in another research paper you got the formula from which you probably forgot to add in the function docstrings.
 
All I need is just to ascertain the formula, so I can go ahead to use it for my FVC estimation as well and also cite the paper too.

I look forward to your response, thanks!

**Comment by dimejimudele** [comment]
HI, I can see that I am very late on this one. But, if I can still be useful, can you try to use this new version of this package and see where it gets you?
