### ISSUE TITLE
For Landsat 8 Collection 2 level 2 products

### ISSUE THREAD

**Issue by JiangThea** [pylandtemp/pylandtemp#4]
I notice that the data you are dealing with is for Collection 1. Do rescaling factors also apply to collection 2? When I tried to modify these factors, it went horribly wrong.

**Comment by JiangThea** [comment]
Landsat 8 Collection 2 level 2 products do not need temperature retrieval.

**Comment by dimejimudele** [comment]
Yes,  exactly. You only need to rescale the band 10 for Landsat 8 Collection 2 level 2. That information probably should be added to the doc of this repo. This repo serves fundamental research that requires comparing different LST computation methods.
