### ISSUE TITLE
Negative Temperature

### ISSUE THREAD

**Issue by asg-me18** [pylandtemp/pylandtemp#8]
Getting negative temperature for Landsat 8 data, which is unrealistic for that region.

**Comment by dimejimudele** [comment]
Hello, can you provide more information?

Which method were you using? which location?

Thanks!

**Comment by asg-me18** [comment]
![306884476_1232897934222133_5060455787767485881_n](https://user-images.githubusercontent.com/94696934/194110453-80b73867-4cb6-43c2-8932-accc7e4192df.jpg)
Thanks for your response. I shared an image in which I provide the four coordinates. I want to know the temperature of that region. I used both methods. I found same result.


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dimejimudele** [comment]
Thanks for getting back. Have you committed your code to github? Can I get access?

Looking forward to your reply.

Thanks

**Comment by asg-me18** [comment]
I don't make any changes in your code.  I just use tutorial code.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dimejimudele** [comment]
Alright, will be right back

**Comment by asg-me18** [comment]
Hi, do you give a check?

**Comment by dimejimudele** [comment]
After troubleshooting, my guess is that you are using the collection 2 Level 2 surface reflectance product which already be themselves provide the surface temperature. For that, you don't need this package; you already have the temperature in Kelvin.

I would love to get the image/collection name that has been used in your process.
